services:

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php

  #  caddy:
  #    image: caddy:latest
  #    environment:
  #      - SITE=localhost:80
  #    volumes:
  #      - ./etc/Caddyfile:/etc/caddy/Caddyfile
  #      - ./www:/srv
  #    ports:
  #      - "80:80"
  #      - "443:443"

  php:
    container_name: php_fpm
    build:
      context: .
    sysctls:
      - net.core.somaxconn=65536
    volumes:
      - ./www:/srv
      - ./etc/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom.conf
      - ./etc/php-custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"

#  swoole:
#    image: phpswoole/swoole:latest
#    container_name: swoole
#    volumes:
#      - ./swoole:/srv
#    command: php /srv/index.php
#    ports:
#      - "9501:9501"
